# 1. 판다스 기초

## 1. 판다스(Pandas)

<img src='https://upload.wikimedia.org/wikipedia/commons/thumb/e/ed/Pandas_logo.svg/500px-Pandas_logo.svg.png' width="400" height ="170" /><br>

▶ 공식문서: https://pandas.pydata.org/docs/index.html

- 파이썬의 대표적인 데이터 분석 도구

- 엑셀과 같이 **행(row)**과 **열(columns)**로 된 데이터 구조를 다룸

- 라이브러리 로드: `import pandas as pd`

- **판다스의 데이터 타입**

    > **Series (시리즈)**<br>
    > 수학적으로 **벡터**의 형태를 가짐 (1차원) <br>
    > 각 요소에 인덱스를 사용할 수 있다 <br>
    > 예시: [1,2,3]

    > **DataFrame (데이터 프레임)** <br>
    > 수학적으로 **행렬**의 형태를 가짐 (2차원) <br>
    > **열(Column)**과 **행(row)**으로 구성 <br>
    > 예시: [ [1,2,3], [4,5,6] ]

<img src='https://pandas.pydata.org/docs/_images/01_table_dataframe.svg' width="700" height ="400" /><br>

In [ ]:
# 판다스 불러오기

# 넘파이 불러오기

▶ 시리즈 만들기 `pd.Series(데이터배열)`

- 1차원 데이터구조의 배열, 다양한 데이터 타입 사용 가능

- 데이터를 다루는 기본 단위

- 인덱스를 사용할 수 있음

    > 인덱스(index)와 값(value)로 이루어짐

- 데이터프레임에서 한 열을 나타내는 자료구조

In [ ]:
# 시리즈 만들기1
data = [1,2,3,4,5]

In [ ]:
# 시리즈 만들기2 - 인덱스 지정

**🧑‍🏫잠깐만**

**딕셔너리**
* 파이썬 자료구조 중 하나

<img src='https://wikidocs.net/images/page/16/02_5_baseball.png' width="200" height ="100" /><br>

> 형태: {'key1':value1, 'key2':value2, 'key3':value3}

In [ ]:
# 시리즈 만들기3 - 딕셔너리로 시리즈 만들기/이름 부여하기
fruit = {'a':'사과','b':'포도','c':'오렌지'}

# name - 시리즈에 이름을 부여해 줌

fruit_series

**numpy**

- 배열을 다룰 수 있는 파이썬 라이브러리. 수치 계산에 특화됨

- 배열의 종류

    <img src='https://velog.velcdn.com/images/jhdai_ly/post/b5e3759c-8ae2-45e7-a89a-e177b70e9fdc/image.png' width="600" height ="300" />

    > 1차원 배열: 벡터, 배열 a 안에 리스트 [1,2,3]이 들어있는 모양
    >
    > 2차원 배열: 행렬, 배열 a 안에 [[1,2,3],[4,5,6]] 두 개의 리스트가 들어가 있는 모양
    >
    > 3차원 배열: 텐서, 배열 a 안에 3개의 리스트가 들어감 [[[]]]

- 넘파이 배열 만들기: `np.array(시퀀스자료형)`

In [ ]:
# 시리즈 만들기5 - 넘파이 배열

* index와 values를 사용하여 인덱스와 값들에 접근할 수 있다.

In [ ]:
# 인덱스 알아보기

In [ ]:
# 값 알아보기

▶ 데이터프레임 만들기

- 2차원 데이터 구조의 배열, 행과 열이 있는 테이블 데이터 구조

- 시리즈가 모여 데이터프레임이 됨

- 각 열은 각각의 데이터 타입을 가짐

In [ ]:
# 데이터프레임 만들기1 - 2차원 배열로 만들기
data = [[1,2,3],
        [4,5,6],
        [7,8,9]]

In [ ]:
# 데이터프레임 만들기2 - 컬럼 지정하기
data = [[1,2,3],
        [4,5,6],
        [7,8,9]]

In [ ]:
# 데이터프레임 만들기3 - 딕셔너리로 생성
cafe = {
        "Name" : ["아이스아메리카노", "카페라떼", "로얄밀크티","자몽 스파클링"],
        "Price": [2600, 2800, 4500, 3800],
        "Sales": [200,100,50,35]
    }

➡️ 딕셔너리의 key값이 column의 이름으로 지정됨

* columns와 values를 사용하여 컬럼과 값들에 접근할 수 있다.

In [ ]:
# 데이터프레임의 열 알아보기

In [ ]:
# 데이터프레임의 값 알아보기

## 2. 데이터 불러오기

▶ CSV파일 데이터 불러오기
> **pd.read_csv (파일경로), pd.read_excel (파일경로)** <br>
> 이때 파일경로는 문자열 형태로 입력
>
> 예) pd.read_csv("/content/sample_data/sample.csv") <br>

In [ ]:
# 데이터 불러오기
# 파일 경로 = "https://raw.githubusercontent.com/agtechresearch/LectureAlgorithm/main/csv/housing.csv"
cali_house = # 작성
cali_house

▶ 🏘️ 캘리포니아 집값 데이터셋

- **longitude**: 위도

- **latitude**: 경도

- **housing_median_age**: 건축물 중위연령

- **total_rooms**: 방의 총 개수

- **total_bedrooms**: 침실 총 개수

- **population**: 인구

- **households**: 가구수

- **median_income**: 중위소득

- **median_house_value**: 주택 중위가격

- **ocean_proximity**: 해안 근접도

## 3. 데이터셋 확인
▶ 전반적인 데이터셋 정보 확인 (**.info()**) <br>
> 데이터셋의 **컬럼정보와 값의 수, 각 컬럼별 데이터타입, 행의 갯수 등**의 정보 <br>

In [ ]:
# 데이터셋 정보 확인

▶ 앞부분 (**.head()**), 마지막부분 (**.tail()**)
> 괄호안에 숫자를 넣어 **앞에서 n개 행(row), 혹은 끝에서 n개 행**을 가져오기

In [ ]:
# 데이터 앞 부분 확인하기

In [ ]:
# 데이터 뒷 부분 확인하기

▶ 데이터셋 기술통계량 확인
> **.describe()** <br>
> 데이터프레임 내부 각 컬럼에 대한 **count, mean, min, max, 사분위값, std 등의 항목을 자동으로 계산** <br>
> .describe() 외 **.min(), .max(), .mean()** 등으로 특정 항목만 구할수도 있음
>

In [ ]:
# 데이터의 통계량 확인하기

▶ 데이터셋 정렬하기

> **sort_index()** <br>
>
>  index 기준으로 정렬
>
>  default는 오름차순이며 ascending의 설정으로 조정가능
>>
>> ascending=False (내림차순으로 정렬)
>

> **sort_values(by =기준컬럼)** <br>
>
>  **값**을 기준으로 행을 정렬
>
>  두개 이상의 컬럼을 지정하여 정렬할 수 있음
>
>  ascending=True (오름차순)이 기본
>
>  컬럼별로 오름차순/내림차순 설정 가능
>

➕ 원본에도 똑같이 적용하고 싶을 경우 **inplace = True**

In [ ]:
# 인덱스 기준으로 정렬하기

In [ ]:
# 값을 기준으로 정렬하기(원하는 값 기준으로 정렬해보세요)

In [ ]:
# 두 개 이상의 컬럼을 기준으로 정렬하기

▶ 데이터 내 고유값 찾기

`unique()`

* 데이터에 고유값들이 어떤 종류가 있는지 알고 싶을 때 사용

* 시리즈, 즉 1개의 컬럼에만 적용 가능(전체 데이터프레임에 적용하면 에러 뜸)

`nunique()`

* 데이터의 고윳값들의 수 출력

`value_counts()`

* 값 별로 데이터 수 출력

* 기본적으로 내림차순으로 정렬 (ascending 옵션으로 지정)

In [ ]:
# ocean_proximity(해안근접도)에 어떤 값들이 있는지 알아보기

In [ ]:
# ocean_proximity(해안근접도) 고유값이 몇 개가 있는지 알아보기

In [ ]:
# ocean_proximity(해안근접도)의 값 별로 데이터의 수가 몇 개가 있는지 알아보기

## 4. 데이터셋 가공
▶ 데이터를 통해 의미있는 결과를 얻기 위해 원본 데이터에서 가공하거나 원하는 데이터를 선택할 수 있음<br>

### (1) 데이터프레임에서 원하는 특정 행 또는 열 가져오기

**1. 열 인덱싱**
> `df['column']`: 데이터프레임에서 열 하나 가져오기
>
> `df[['column']]`: 열 하나 가져오기, 데이터프레임 형태로 출력
>
> `df[['column1','column2']]`: 여러개의 열을 부를 때는 리스트로

In [ ]:
# 데이터프레임에서 열 하나 가져오기

In [ ]:
# 데이터프레임에서 열 가져오는데 데이터프레임 형태로 보기

In [ ]:
# 여러개의 열 가져오기

**2. 행 인덱싱**

> 슬라이싱 형식으로 가져옴

In [ ]:
# 데이터프레임에서 3번행부터 8번행까지 가져오기

**3. .loc, .iloc 사용하기**

**(1) iloc**

> 정수번호로 인덱싱, 슬라이싱의 경우 **끝번호 포함 안됨**
>
> `df.iloc[행,열]`

**행** : 인덱스번호 1개 , [ 인덱스 여러개 ] , [ 인덱스번호 슬라이싱]

**열** : 칼럼번호 1개 , [ 칼럼번호 여러개 ] , [ 칼럼번호 슬라이싱 ]

In [ ]:
# 여러개의 행 가져오기(3번행부터 8번행까지) - iloc도 가능

In [ ]:
# 원하는 행과 열 지정하여 가져오기1
# 행 - 0부터 5번째 행
# 열 - 0부터 1번째 열

In [ ]:
# 원하는 행과 열 지정하여 가져오기2
# 행 - 1,3,5 번째 행
# 열 - 0부터 1번째 열

**(2) loc**
> 라벨값으로 인덱싱(값/boolean index), 슬라이싱의 경우 **끝번호 포함됨**
>
> `df.loc[행,열]`

**행** : 인덱스번호 1개 , [ 인덱스 여러개 ] , [ 인덱스번호 슬라이싱]

**열** : 칼럼 1개 , [ 칼럼 여러개 ] , [ 칼럼이름 슬라이싱 ]

In [ ]:
# 'total_rooms'와 'total_bedrooms'열의 행 6번째까지 가져오기

In [ ]:
# 'longitude'부터 'median_house_value'까지, 행은 1~5번째까지 가져오기

* loc는 boolean으로 특정 값을 가져올 수 있다 (조건)

> 관계연산자 및 논리연산자 사용 가능
>
> 행의 조건을 가지고 원하는 열을 골라서 추출할 수 있다

In [ ]:
# 특정 조건에 맞는 행 가져오기
# 총 가구수가 4000이 넘고 중위소득이 5만달러가 넘는 지역의 위치('longitude','latitude') 알아보기

### (2) 데이터셋 결측치 확인
>  실제 데이터셋 에서는 **측정되지 않았거나, 누락 등 알수없는 이유**로 데이터프레임 상에서 **NaN(Not a Number)값**인 데이터가 있음 <br>
>
> 특히 NaN값은 제거하거나 다른 적절한 값으로 채우지 않을 경우, **연산시 오류**를 일으키므로 데이터셋 가공 전 **꼭 확인** 필요
>
> * 결측값 확인 <br>
>  **isnull(), isnull().sum()**
>
> * 결측값 채우기 <br>
>  **fillna(특정값)**

In [ ]:
# 결측값이 각 컬럼에 총 몇 개 있는지 알아보자

In [ ]:
# 결측치 채우기
cali_house_1 =  # 다른 변수에 따로 지정

In [ ]:
# 결측값 확인

In [ ]:
# 결측치가 포함된 행이 어디에 있는지 알아보기

▶ 데이터 삭제하기

* 결측값이 있는 행, 열 제거 **dropna()**
>
> `dropna()`: 어떤 행이든 하나 이상의 결측치가 있으면 해당 행 제거
>
>  `dropna(axis=1)`: 어떤 열이든 하나 이상의 결측치가 있으면 해당 열 제거
>
> `dropna(subset=['컬럼'])`: 특정 열에 결측치가 있는 행만 제거

> axis=0 : 행방향(결측치가 있는 행 제거) <br> axis=1 : 열방향(결측치가 있는 열 제거)

In [ ]:
# 데이터 생성
cafe1 = {
        "Name" : ["아이스아메리카노", "카페라떼", "로얄밀크티","자몽 스파클링"],
        "Price": [2600, 2800, np.NaN, 3800],
        "Sales": [200,np.NaN,50,35]
    }
cafe_df1 = pd.DataFrame(cafe1)
cafe_df1

In [ ]:
# 결측치가 있는 행 제거(cafe_df1)

In [ ]:
# 결측치가 있는 열 제거(cafe_df1)

In [ ]:
# 특정 열에 결측치가 있는 행만 제거

▶ 데이터 삭제하기

* 원하는 행, 열 제거 **drop()**
>
> 행(하나): 데이터프레임**.drop(인덱스,axis=0)**
>
> 행(여러개): 데이터프레임**.drop(index=삭제할 인덱스 리스트)**
>
> 열(하나): 데이터프레임**.drop('컬럼명', axis=1)**
>
> 열(여러개): 데이터프레임**.drop(['컬럼1','컬럼2'], axis=1)**

In [ ]:
# 행 하나 삭제

In [ ]:
# 여러개의 행 삭제

In [ ]:
# 하나의 열 삭제

In [ ]:
# 여러개의 열 삭제

### (3) 그룹 연산을 통해 특정 조건에 따라 그룹 나누기
> **groupby('컬럼')** <br>
> 주로 그룹연산과 함께 mean(), size(), sum()등을 사용 <br>
> + 컬럼값에 [ ]를 이용하여 [컬럼1, 컬럼2] 형식으로 입력할 경우, 컬럼1의 값들 안에서 컬럼2의 값으로 분리된다.
>

In [ ]:
# 해안근접도(5개의 범주)에 따른 각 컬럼의 평균 알아보기

In [ ]:
# 해안근접도와 인구수에 따른 각 컬럼의 최소값 알아보기

In [ ]:
# 두 개 이상의 연산 사용하기

### (4) 데이터셋 합치기
> * **.concat( [ 합칠 데이터프레임 나열 ] )** <br>
>  두 데이터프레임을 **단순하게 합칠 때** 사용 <br>
> 행 또는 열 방향으로 연결 <br>
> 기본값: `axis=0` (행 방향, 위/아래 방향으로 연결) <br>
> `axis=1` (열 방향, 좌/우 방향으로 연결)
>
> * **.merge( 데이터프레임1, 데이터프레임2, on=공통컬럼명 )** <br>
>  두 데이터프레임을 **공통된 항목(key값,컬럼)을 기준으로 합칠 때** 사용(병합)
>

In [ ]:
# 데이터 생성
# 데이터 1
cafe = {
        "Name" : ["아이스아메리카노", "카페라떼", "로얄밀크티","자몽 스파클링"],
        "Price": [2600, 2800, 4500, 3800],
    }
df1 = pd.DataFrame(cafe)
df1

In [ ]:
# 데이터 2
sales = {"Sales": [200,100,50,35]}
df2 = pd.DataFrame(sales)
df2

In [ ]:
# 두 데이터 합치기 - 행과 행

In [ ]:
# 두 데이터 합치기 - 열과 열

In [ ]:
# 데이터 만들기
df1 = pd.DataFrame({
    '책이름': ['모순', '모래알만 한 진실이라도', '사피엔스', '돈의 심리학', '원씽'],
    '출판일': ['2013-04-01', '2022-06-30', '2023-04-01', '2023-11-06', '2013-08-30'],
    '분류': ['소설', '에세이', '인문', '경제', '자기계발']})
df1

In [ ]:
df2 = pd.DataFrame({
    '책이름': ['코스모스', '모래알만 한 진실이라도', '모순', '공정하다는 착각', '사피엔스'],
    '가격': ['19,900원', '17,000원', '13,000원', '18,000원', '26,800원']})
df2

* on = '기준열'

> 공통이 되는 기준 열이 여러개일 때
>
> `pd.merge(df1, df2, on=['열1','열2']`
>
> 두 데이터프레임의 기준이 되는 열 이름이 다를 때
>
> `pd.merge(df1, df2, left_on='왼쪽 열', right_on='오른쪽 열')`

In [ ]:
# 두 데이터프레임 합치기 - 책이름을 기준으로

In [ ]:
# 새 데이터 생성

In [ ]:
# 병합하려는 기준 열이 각각 이름이 다를 때 지정하기

* how = join 방식

<img src='https://img1.daumcdn.net/thumb/R1280x0/?scode=mtistory2&fname=https%3A%2F%2Fblog.kakaocdn.net%2Fdn%2FmUaDA%2FbtqKSfLmuhO%2FK3cMP0Znh9NtUoRTODNbZK%2Fimg.png' width="850" height ="200" />

In [ ]:
# 두 데이터프레임 병합 - how 사용(디폴트 inner)

In [ ]:
# 두 데이터프레임 병합 - how 사용, 왼쪽 데이터 기준으로 병합